server:
  port: 9200
spring:
  application:
    name: pnmins_min
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://47.101.188.136:3306/pnmis_min?useUnicode=true&characterEncoding=utf8
      username: pnmis_min
      password: pnmis_min123
      driver-class-name: com.mysql.jdbc.Driver
    ###################以下为druid增加的配置###########################
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
    # 配置获取连接等待超时的时间
      maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
    ###############以上为配置druid添加的配置########################################
  #redis
  redis:
    database: 0
    host: 10.20.92.49
    port: 7007
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 1
    timeout: 60s

mybatis:
  mapper-locations: classpath*:sqlmapper/*Mapper.xml

logging:
  level:
    root: info
    com.hoperun.emp.phges.dao.mapper: debug
  config: classpath:logback.xml



